# Generated by Django 5.0 on 2023-12-20 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_registration', '0002_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
